// <copyright file="WorkflowEventSubscription.cs" company="Endjin Limited">
// Copyright (c) Endjin Limited. All rights reserved.
// </copyright>

namespace Marain.Workflows
{
    /// <summary>
    /// Configuration for an individual subscriber to CloudEvents generated by the workflow engine.
    /// </summary>
    public class WorkflowEventSubscription
    {
        /// <summary>
        /// Gets or sets the URL of the external service that this action will POST to when executed.
        /// </summary>
        public string ExternalUrl { get; set; }

        /// <summary>
        /// Gets a value indicating whether requests to the external service should be authenticated using the managed
        /// service identity of the hosting service.
        /// </summary>
        public bool AuthenticateWithManagedServiceIdentity => !string.IsNullOrEmpty(this.MsiAuthenticationResource);

        /// <summary>
        /// Gets or sets the resource for which to authenticate when
        /// <see cref="AuthenticateWithManagedServiceIdentity"/> is true.
        /// </summary>
        /// <remarks>
        /// <para>
        /// When the external service hosted in Azure and has Easy Auth enabled, this will be the
        /// GUID of the AAD App that Azure created to represent that application.
        /// </para>
        /// </remarks>
        public string MsiAuthenticationResource { get; set; }
    }
}