// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Marain.Workflows.Functions.Specs.MessageIngestionHost
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("SendTrigger")]
    [NUnit.Framework.CategoryAttribute("perFeatureContainer")]
    public partial class SendTriggerFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SendTrigger.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SendTrigger", "\tIn order to tell the workflow engine to carry out actions\r\n\tAs an external user " +
                    "of the workflow engine\r\n\tI want to send a trigger ", ProgrammingLanguage.CSharp, new string[] {
                        "perFeatureContainer"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Send a trigger")]
        public virtual void SendATrigger()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Send a trigger", null, ((string[])(null)));
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given("I start a functions instance for the local project \'Endjin.Workflow.Functions.Mes" +
                    "sageIngestionHost\' on port 7071", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And("I start a functions instance for the local project \'Endjin.Operations.Functions.O" +
                    "perationsControlHost\' on port 7078", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "TriggerName"});
            table15.AddRow(new string[] {
                        "TestTrigger"});
#line 10
 testRunner.And("I have an object of type \"application/vnd.marain.workflows.hosted.trigger\" called" +
                    " \"trigger\"", ((string)(null)), table15, "And ");
#line 13
 testRunner.And("I am listening for events from the event hub", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.When("I post the object called \"trigger\" to the endpoint \"http://localhost:7071/trigger" +
                    "s\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 15
 testRunner.And("wait for up to 3 seconds for incoming events from the event hub", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.Then("I should have received a 202 status code from the HTTP request", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.And("I should have received a trigger containing JSON data that represents the object " +
                    "called \"trigger\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.And("I should not have received an exception from processing events", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Send multiple triggers")]
        public virtual void SendMultipleTriggers()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Send multiple triggers", null, ((string[])(null)));
#line 20
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 21
 testRunner.Given("I start a functions instance for the local project \'Endjin.Workflow.Functions.Mes" +
                    "sageIngestionHost\' on port 7071", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 22
 testRunner.And("I start a functions instance for the local project \'Endjin.Operations.Functions.O" +
                    "perationsControlHost\' on port 7078", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "TriggerName"});
            table16.AddRow(new string[] {
                        "TestTrigger0"});
            table16.AddRow(new string[] {
                        "TestTrigger1"});
            table16.AddRow(new string[] {
                        "TestTrigger2"});
            table16.AddRow(new string[] {
                        "TestTrigger3"});
            table16.AddRow(new string[] {
                        "TestTrigger4"});
            table16.AddRow(new string[] {
                        "TestTrigger5"});
            table16.AddRow(new string[] {
                        "TestTrigger6"});
            table16.AddRow(new string[] {
                        "TestTrigger7"});
            table16.AddRow(new string[] {
                        "TestTrigger8"});
            table16.AddRow(new string[] {
                        "TestTrigger9"});
#line 23
 testRunner.And("I have objects of type \"application/vnd.marain.workflows.hosted.trigger\" called \"" +
                    "triggers\"", ((string)(null)), table16, "And ");
#line 35
 testRunner.And("I am listening for events from the event hub", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.When("I post the objects called \"triggers\" to the endpoint \"http://localhost:7071/trigg" +
                    "ers\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 37
 testRunner.And("wait for up to 3 seconds for incoming events from the event hub", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.Then("I should have received 10 202 status codes from the HTTP requests", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 39
 testRunner.And("I should have received at least 10 triggers containing JSON data that represents " +
                    "the object called \"triggers\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("I should not have received an exception from processing events", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
