// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Marain.Workflows.EngineHost.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Defines headers for getWorkflow operation.
    /// </summary>
    public partial class GetWorkflowHeaders
    {
        /// <summary>
        /// Initializes a new instance of the GetWorkflowHeaders class.
        /// </summary>
        public GetWorkflowHeaders()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetWorkflowHeaders class.
        /// </summary>
        /// <param name="eTag">The etag for the updated tenant</param>
        public GetWorkflowHeaders(string eTag = default(string))
        {
            ETag = eTag;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the etag for the updated tenant
        /// </summary>
        [JsonProperty(PropertyName = "ETag")]
        public string ETag { get; set; }

    }
}
