// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Marain.Workflows.EngineHost.Client.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Workflow
    {
        /// <summary>
        /// Initializes a new instance of the Workflow class.
        /// </summary>
        public Workflow()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Workflow class.
        /// </summary>
        public Workflow(string id, string initialStateId, IDictionary<string, WorkflowState> states, string description = default(string), string displayName = default(string))
        {
            Id = id;
            Description = description;
            DisplayName = displayName;
            InitialStateId = initialStateId;
            States = states;
            CustomInit();
        }
        /// <summary>
        /// Static constructor for Workflow class.
        /// </summary>
        static Workflow()
        {
            ContentType = "application/vnd.marain.workflows.workflow";
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "initialStateId")]
        public string InitialStateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "states")]
        public IDictionary<string, WorkflowState> States { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "contentType")]
        public static string ContentType { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Id == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Id");
            }
            if (InitialStateId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "InitialStateId");
            }
            if (States == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "States");
            }
            if (States != null)
            {
                foreach (var valueElement in States.Values)
                {
                    if (valueElement != null)
                    {
                        valueElement.Validate();
                    }
                }
            }
        }
    }
}
