openapi: '3.0.0'
info:
  description: This is the main host function for the Marain Workflow service. Triggers can be POSTed to the provided endpoint to be enqueued and executed by the engine.
  version: 1.0.0
  title: Marain Workflow - Engine
  contact:
    email: hello@endjin.com
servers: 
  - url: https://workflow-engine.marain.io
paths:
  /{tenantId}/marain/workflow/engine/workflowinstances:
    post:
      summary: Start a new instance of a workflow
      operationId: startWorkflowInstance
      parameters:
        - $ref: '#/components/parameters/tenantId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StartWorkflowRequest"
      responses:
        201:
          description: The new workflow instance has been successfully created.
        400:
          description: The supplied data was invalid or incomplete.
        404:
          description: The specified workflow does not exist.
        default:
          description: Unexpected error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
  /{tenantId}/marain/workflow/engine/workflowinstances/{workflowInstanceId}/triggers:
    post:
      summary: Dispatch a trigger for processing by a specific workflow instance.
      operationId: sendTrigger
      requestBody:
        description: New trigger to be processed by the engine
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trigger"
      parameters:
        - $ref: '#/components/parameters/tenantId'
        - $ref: '#/components/parameters/workflowInstanceId'
      responses:
        200:
          description: The trigger has been successfully processed by the specified workflow instance.
        400:
          description: The supplied data could not be deserialized into a valid trigger.
        404:
          description: The specified workflow instance does not exist.
        default:
          description: Unexpected error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
components:
  schemas:
    StartWorkflowRequest:
      properties:
        requestId:        
          type: string
          nullable: true
          example: "4629f9f3-a706-4901-a215-df8313376b52"
          description: Unique Id for this request
        contentType:
          type: string
          enum:
            - "application/vnd.marain.workflows.hosted.startworkflowinstancerequest"
          example: "application/vnd.marain.workflows.hosted.startworkflowinstancerequest"
        workflowId:        
          type: string
          example: "e7fe35a4-519d-4d5c-a338-a4d57a970666"
          description: The unique Id of the workflow to start the instance from
        workflowInstanceId:
          type: string
          nullable: true
          example: "a29caa9f-0150-42f8-9e7b-a477fcb18112"
          description: The Id of the new workflow instance
        context:
          type: object
          nullable: true
          additionalProperties:
            type: string
          description: Parameters for the new workflow instance. This will be processed on the server as a list of key/value pairs.
          example:
            "Name": "John Smith"
            "Age": "42"
      required:
        - workflowId
        - contentType

    Trigger:
      properties:
        id:
          type: string
          nullable: true
          example: "4629f9f3-a706-4901-a215-df8313376b52"
          description: Unique Id for this trigger. The Id will be used internally to trace the path of the trigger through the workflow engine and can be used to retrieve the status of the trigger. If omitted, a trigger Id will be generated by the server.
        contentType:
          type: string
          enum:
            - "application/vnd.marain.workflows.hosted.trigger"
          example: "application/vnd.marain.workflows.hosted.trigger"
        triggerName:
          type: string
          description: The name of the trigger. This will correspond to internal conditions and used to determine which transitons this trigger can select.
          example: Publish
        subjects:
          type: array
          nullable: true
          description: A list of Ids that can be used when retrieving workflow instances that may need to process this trigger. If left blank, all Waiting workflow instances will try to process the trigger, so it is strongly recommended that you always supply a value. If possible, use the Id of the specific workflow instance that you want to process the trigger.
          example:
            - "74f4ce70-afa9-40bb-8516-7680e2604069"
            - "2d4722c1-3915-4b3b-a338-15595d98f01f"
          items:
            type: string
        parameters:
          type: object
          nullable: true
          additionalProperties:
            type: string
          description: Parameters for this trigger. This will be processed on the server as a list of key/value pairs - complex objects should not be used.
          example:
            "Name": "John Smith"
            "Age": "42"
      required:
        - contentType
        - triggerName
        - subjects

    ############################################################################
    # RFC 7807 Problem Details response definition
    # https://tools.ietf.org/html/rfc7807
    ############################################################################
    ProblemDetails:
      required:
        - status
        - detail
      properties:
        status:
          type: integer
          format: int32
        detail:
          type: string
        title:
          type: string
        instance:
          type: string
          format: url
        type: 
          type: string
          format: url
        validationErrors: 
          type: array
      additionalProperties: true
      
  parameters:
    tenantId:
      name: tenantId
      in: path
      x-ms-parameter-location: method
      description: The tenant within which the request should operate
      required: true
      schema:
        type: string
    workflowInstanceId:
      name: workflowInstanceId
      in: "path"
      description: The Id of the workflow instance to apply the trigger to
      required: true
      schema:
        type: string