openapi: "3.0.0"
info:
  description: "This is the entry point for new messages into the Endjin Workflow service. Messages can be POSTed to the provided endpoint to be enqueued and executed by the engine."
  version: "1.0.0"
  title: "Endjin Workflow - Message Ingestion"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "hello@endjin.com"
servers:
  - url: "https://workflow-messages.endjin.com"
paths:
  /triggers:
    post:
      tags:
      - "messages"
      summary: "Send a new trigger into the workflow engine"
      description: ""
      operationId: "sendTrigger"
      requestBody:
        description: "New trigger to be processed by the engine"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Trigger"
      responses:
        202:
          description: "The trigger has been enqueued for processing by the workflow engine."
          headers:
            Location:
              description: A link to endpoint in the Operations Status API for this operation
              schema:
                type: string
        400:
          description: "The supplied data could not be deserialized into a valid trigger."
        default:
          description: unexpected error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
  /startnewworkflowinstancerequests:
    post:
      tags:
      - "messages"
      summary: "Send a request to start a new workflow instance into the workflow engine"
      description: ""
      operationId: "sendStartNewWorkflowInstanceRequest"
      requestBody:
        description: "Details of the new workflow instance to be started"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StartNewWorkflowInstanceRequest"
      responses:
        202:
          description: "The request has been enqueued for processing by the workflow engine."
          headers:
            Location:
              description: A link to endpoint in the Operations Status API for this operation
              schema:
                type: string
        400:
          description: "The supplied data could not be deserialized into a valid request."
        default:
          description: unexpected error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
components:
  schemas:
    Trigger:
      description: A trigger that may cause one or more workflow instances to change state
      type: "object"
      format: "application/vnd.marain.workflows.hosted.trigger"
      properties:
        id:
          type: "string"
          nullable: true
          example: "4629f9f3-a706-4901-a215-df8313376b52"
          description: "Unique Id for this trigger. The Id will be used internally to trace the path of the trigger through the workflow engine and can be used to retrieve the status of the trigger. If omitted, a trigger Id will be generated by the server."
        contentType:
          type: "string"
          enum:
            - "application/vnd.marain.workflows.hosted.trigger"
          example: "application/vnd.marain.workflows.hosted.trigger"
        triggerName:
          type: "string"
          description: "The name of the trigger. This will correspond to internal conditions and used to determine which transitons this trigger can select."
          example: "Publish"
        subjects:
          type: "array"
          nullable: true
          description: "A list of Ids that can be used when retrieving workflow instances that may need to process this trigger. If left blank, all Waiting workflow instances will try to process the trigger, so it is strongly recommended that you always supply a value. If possible, use the Id of the specific workflow instance that you want to process the trigger."
          example: ["74f4ce70-afa9-40bb-8516-7680e2604069", "2d4722c1-3915-4b3b-a338-15595d98f01f"]
          items:
            type: "string"
        parameters:
          type: "object"
          nullable: true
          additionalProperties:
            type: "string"
          description: "Parameters for this trigger. This will be processed on the server as a list of key/value pairs - complex objects should not be used."
          example:
            "Name": "John Smith"
            "Age": "42"
      required:
        - contentType
        - triggerName
    StartNewWorkflowInstanceRequest:
      description: "A request to create a new instance of a workflow"
      type: "object"
      format: "application/vnd.marain.workflows.hosted.startworkflowinstancerequest"
      properties:
        requestId:
          type: "string"
          nullable: true
          example: "4629f9f3-a706-4901-a215-df8313376b52"
          description: "Unique Id for this request. The Id will be used internally to trace the path of the request through the workflow engine and can be used to retrieve the status of the trigger. If omitted, a request Id will be generated by the server."
        contentType:
          type: "string"
          enum:
            - "application/vnd.marain.workflows.hosted.startworkflowinstancerequest"
          example: "application/vnd.marain.workflows.hosted.startworkflowinstancerequest"
        workflowId:
          type: "string"
          example: "80e03354-959b-4c23-9860-2f692b90ebc5"
          description: "Id of the workflow to start an instance of. This should match the Id of an existing workflow stored within the hosted workflow service."      
        workflowInstanceId:
          type: "string"
          nullable: true
          example: "e58627e6-91eb-4283-a171-53414aa6618b"
          description: "Id to give the new workflow instance. If omitted, an Id will be generated."
        context:
          type: "object"
          nullable: true
          additionalProperties:
            type: "string"
          description: "Parameters for this trigger. This will be processed on the server as a list of key/value pairs - complex objects should not be used."
          example:
            "Name": "John Smith"
            "Age": "42"
      required:
        - contentType
        - workflowId
    ProblemDetails:
      description: Information about a failed operation
      required:
        - status
        - detail
      properties:
        status:
          type: integer
          format: int32
        detail:
          type: string
        title:
          type: string
        instance:
          type: string
          format: url
        type: 
          type: string
          format: url
        validationErrors: 
          type: array
      additionalProperties: true